logLevel = "DEBUG"
#debug = true

defaultEntryPoints = ["http", "https", "ws", "wss"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
    minVersion = "VersionTLS12"
    cipherSuites = [
      "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
      "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305",
      "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
      "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
      "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
      "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
      "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256",
      "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256",
      "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA",
      "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA",
      "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA",
      "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA",
    ]
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/traefik/cert/secureskye.crt"
      keyFile = "/etc/traefik/cert/secureskye.key"

# Enable management UI
[web]

# Use Consul KV store (for ACME)
[consul]
endpoint = "discovery:8500"

# Load services from Consul
[consulCatalog]
endpoint = "discovery:8500"
domain = "secureskye-demo.trilliumsecure.com"

# Automatic certificate generation
[acme]
email = "dominik.nakamura@trilliumsecure.com"
storage = "traefik/acme/account"
# Staging server for testing
#caServer = "https://acme-staging.api.letsencrypt.org/directory"
entryPoint = "https"
#acmeLogging = true
  [acme.dnsChallenge]
  provider = "godaddy"

[[acme.domains]]
  main = "secureskye-demo.trilliumsecure.com"
[[acme.domains]]
  main = "ota.trilliumsecure.com"
