= OTA-Update package format and creation
:toc: left
:homepage: http://trilliumsecure.com
:icons: font
:source-highlighter: pygments
:sectanchors:

== OTA archive information
Package is supported in `zip` or `tar.gz` format.
Size of the package must be less than *10 MB*.
Archive has to contain a `metadata.yaml` file as the first entry in the archive and a `ecus` folder.

=== Metadata file information
Metadata file has to contains the following information.
[source,yaml]
----
family: <vehicle-model-name> <1>
version: <update-version> <2>
updateType: <update-type> <3>
ecus: <4>
- id: <ecu-id> <5>
  version: <ecu-version> <6>
  items: <7>
  - name: <item-name> <8>
  - checksum: <item-checksum> <9>
----

<1> The vehicle model this update is for. This has to be equal to one of the vehicle models' name.

<2> Version of the update. Has to follow https://semver.org[SemVer^].

<3> The type of update: experimental, beta, production.

<4> The different ECUs that have to be updated.

<5> Unique identifier of the ECU. This has to be a hex string of 32 bytes encoded data,
include 4 chunks of 8 byte blocks which describe hardware version, software version, callibration version and special version.

<6> The version of the update for a single ECU. Has to follow https://semver.org[SemVer^].

<7> Contains one or more actual files that are targeted to the ECU. This is usually the update data, but can technically be anything.

<8> The name of the update data. This has to match with the file in the archive.

<9> A SHA-256 digest of the content of the update data.


=== Ota Archive Structure
----
/ecus/<ecu-id>/<item-name>
----
This has to exactly match with the information from the metadata.yaml.
----
Example: `/ecus/0000000000000002000000000000000300000000000000040000000000000005/file1.img`
----

== API usage

[#api-upload]
=== Upload OTA archive

Upload an OTA archive to the server.

[source,bash]
----
curl -X POST /api/ota \
  -H "Authorization: Bearer {{access_token}}" \
  -F "file=ota-archive-file"
----

[%autowidth.stretch]
|====
|Attribute|Type  |Required|Description

|file     |string|true    |The file to be uploaded
|====

[#api-publish]
=== Publish OTA archive

Publish an uploaded archive.

[source,bash]
----
curl -X PUT /ota/{id}/publish \
  -H "Authorization: Bearer {{access_token}}"
----

[%autowidth.stretch]
|====
|Attribute|Type  |Required|Description

|id       |string|true    |Identifier of the archive to publish
|====

=== Download OTA image

Download an image of an archive by image ID.

[source,bash]
----
curl -X GET /ota/images/{id} \
  -H "Authorization: Bearer {{access_token}}"
----

[%autowidth.stretch]
|====
|Attribute|Type  |Required|Description

|id       |string|true    |unique id of an image in the archive
|====

[#api-list]
=== List available updates

Get a list of all available updates, including older or already applied ones as well. To only list newer updates, see
the <<api-list-filtering>> below.

[source,bash]
----
curl -X GET /ota/metadata \
  -H "Authorization: Bearer {{access_token}}" \
  -H "Accept: application/json"
----

[#api-list-filtering]
==== Filtering

The list can be filtered by `family` and/or a specific version to only list metadata newer than the one provided.

[source,bash]
----
curl -X GET /ota/metadata?family={archive-family}&fromVersion={archive-version} \
  -H "Authorization: Bearer {{access_token}}" \
  -H "Accept: application/json"
----

[%autowidth.stretch]
|====
|Attribute  |Type  |Required|Description

|family     |string|no      |Vehicle family to filter by
|fromVersion|string|no      |A semantic version as minimum to filter older updates
|====

=== Get OTA archive by ID

Get te information of an archive by ID.

[source,bash]
----
curl -X GET /ota/metadata/{id} \
  -H "Authorization: Bearer {{access_token}}" \
  -H "Accept: application/json"
----

[%autowidth.stretch]
|====
|Attribute|Type  |Required|Description

|id       |string|true    |unique id of an archive
|====

=== Delete OTA archive by ID

Delete an uploaded archive by ID.

[source,bash]
----
curl -X DELETE /ota/metadata/{id} \
  -H "Authorization: Bearer {{access_token}}"
----

[%autowidth.stretch]
|====
|Attribute|Type  |Required|Description

|id       |string|true    |unique id of the archive
|====


== Download available Updates

First you will use the <<api-upload>> API to upload the archive to the server.
Then you will use the <<api-publish>> API to publish the archive.
After successfully published, the vehicles will receive notify and will be able to install the archive.

The notification will be sent through a WebSocket service to:

[source]
----
ota/updateFeeds/{family}
----

In case you can't use WebSockets or prefer traditional REST calls, you can also call the <<api-list>> API periodically.

=== Example

We have an example of update package name `metadata.zip` - 38Kb.

the `metadata.yaml` holds these information

[#example-metadata]
[source,yaml]
----
family: test
version: 1.0.0
update-type: experimental
ecus:
- id: "0000000000000000000000000000000100000000000000020000000000000003"
  version: 1.0.0
  items:
  - name: image_1_1.txt
    checksum: d4ce21416b7d15e26e8a4b2dd5dd04e44c0ef517408d5fedbe13a40225396e41
- id: "0000000000000001000000000000000200000000000000030000000000000004"
  version: 1.0.0
  items:
  - name: image_2_1.txt
    checksum: df8ed264a31dd75e009de6af61e10ff305f89b35b09c24a1546281eff9aba778
- id: "0000000000000002000000000000000300000000000000040000000000000005"
  version: 1.0.0
  items:
  - name: img_gw.jpg
    checksum: c160fa1bc488af7f48984bd627bc5cbc5a20b98eaaf11af92e99a206b376252d
----

==== Through the API

The <<api-upload>> request will look like this

[source,bash]
----
curl -X POST
  /api/ota
  -H "Authorization: Bearer {{access_token}}"
  -H "content-type: multipart/form-data"
  -F "file=metadata.zip"
----

After the successful upload, the archive will has an ID. In this case is the *example ID* `88af7f48984bd627bc5cb`.

And the <<api-publish>> will look like this:

[source,bash]
----
curl -X PUT
  /ota/88af7f48984bd627bc5cb/publish
  -H "Authorization: Bearer {{access_token}}"
----

==== In the UI

. After you created your update package for <<example-metadata,metadata.zip>>, drop it on the UI at the
  `OTA upload Image` page.
. If the file is valid, the `Upload` button will be available. Once you press the button, the <<api-upload>> API
  will be called.
. When the upload is completed you will be taken to the `Image Archive` details page.
. This page provide you the information of the archive, the number of the ECUs get updated and their details.
. At `Image Archive` page, you can use the `Publish` button to publish the archive by the <<api-publish>> API
. Client will get a notification about the update, when a update package is available, depend on the `Family` of the
  package.
. Then after the archive has been published successfully, client will be able to install the archive
