#
# Copyright (C) 2017-2018 Trillium Inc. <support@trilliumsecure.com>
#

spring:
  datasource:
    url: jdbc:postgresql://192.168.10.220:5432/secureskye
    username: postgres
    password: postgres
  data:
    mongodb:
      host: 192.168.10.220
      database: secureskye
      username: mongodb
      password: mongodb
  cloud:
    consul:
      host: 192.168.10.220
      discovery:
        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        health-check-path: /actuator/health
        tags:
          - >-
            traefik.frontend.rule=
            Path:
            /api/vehicles,
            /api/vehicles/{id},
            /api/vehicles/{id}/image,
            /api/vehicles/{id}/rename,
            /api/vehicles/{id}/2fa,
            /api/vehicles/{id}/display-settings,
            /api/vehicles/models,
            /api/vehicles/models/{id},
            /api/vehicles/models/{id}/2fa,
            /api/vehicles/models/{id}/settings,
            /api/internal/vehicles/{id},
            /api/internal/vehicles/{id}/connection,
            /api/internal/vehicles/{id}/connection/{status},
            /api/vehicles/statistics,
            /api/vehicles/statistics/online,
            /api/internal/vehicles/{id}/update-count,
            /api/internal/vehicles/{id}/alert-count,
            /api/vehicles/search,
            /api/vehicles/makers,
            /api/vehicles/makers/{id},
            /api/vehicles/security,
            /api/vehicles/security/{id},
            /api/vehicles/{id}/security-status,
            /api/vehicles/{id}/security-software,
            /api/vehicles/security-setting,
            /api/vehicles/security/security-setting,
            /api/vehicles/security/security-setting/{id}
          - traefik.frontend.priority=10

security:
  oauth2:
    secureskye:
      client:
        access-token-uri: http://saa/saa/oauth/token
        client-id: secureskye-vehicle-admin-service
        client-secret: secureskye-service
        scope: none
        added-info: jwt

management:
  endpoints:
    web:
      exposure:
        include: info,health,metrics,prometheus

socketio:
  service-id: socketio
  path: /socketio/socket.io

device-configuration:
  connection:
    #The lost signal time in nanosecond, default is 10 minutes = 600000000000 nanoseconds
    lost-signal-time: 10m

---
spring:
  profiles: local
  datasource:
    url: jdbc:postgresql://localhost:5432/secureskye
  data:
    mongodb:
      host: localhost
  cloud:
    consul:
      host: localhost
server:
  port: 11020

---
spring:
  profiles: debug
  jpa:
    hibernate:
      ddl-auto: validate

---
spring:
  profiles: docker
  datasource:
    url: jdbc:postgresql://postgres:5432/secureskye
  data:
    mongodb:
      # Disable sharding for now
      #host: mongodb-router-1,mongodb-router-2
      host: mongodb
  cloud:
    consul:
      host: discovery
      discovery:
          instance-id: ${spring.application.name}:${HOSTNAME}
          prefer-ip-address: true

server:
  undertow:
    accesslog:
      enabled: true
      dir: /var/log

logging:
  path: /var/log
  level:
    root: WARN
    jp.co.trillium.*: INFO

---
spring:
  profiles: docker-local
  data:
    mongodb:
      host: mongodb
---
spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
