/*
 * @Author: NhuHH 
 * @Date: 2018-11-14 11:38:20 
 * @Last Modified by: NhuHH
 * @Last Modified time: 2018-11-29 14:23:30
 */
const PREFIX = 'ROLE_INFORMATION_OF_USER_FORM_';
export const actionTypes = {
  TOOGLE_USER_FORM_ROLE_INFORMATION: `${PREFIX}TOOGLE_USER_FORM_ROLE_INFORMATION`,
  GET_ROLE_FORM_ROLE_INFORMATION: `${PREFIX}GET_ROLE_FORM_ROLE_INFORMATION`,
  HANDLE_DELETE: `${PREFIX}HANDLE_DELETE`,
  DELETE_ROLE_INFORMATION: `${PREFIX}DELETE_ROLE_INFORMATION`,
  GET_ROLE_INFROMATION: `${PREFIX}GET_ROLE_INFROMATION`,
  GET_NEW_ROLE_INFROMATION: `${PREFIX}GET_NEW_ROLE_INFROMATION`,
  RESET_DATA: `${PREFIX}RESET_DATA`,
};
