scrape_configs:
- job_name: 'spring'
  scrape_interval: 15s
  metrics_path: '/actuator/prometheus'
  consul_sd_configs:
  - server: discovery:8500
    services:
    - ie-main
    - ixs-main
    - licensing-main
    - notification-main
    - uaa
    - saa
    - ota-vehicle
    - user-admin
    - vehicle-admin
    - vehicle-message
    - vehicle-registry
  relabel_configs:
  - source_labels: [__meta_consul_service]
    regex: '^(uaa|saa)$'
    replacement: '/$1/actuator/prometheus'
    target_label: __metrics_path__
