/*
 * @Author: NhuHH 
 * @Date: 2018-11-13 08:50:15 
 * @Last Modified by: LoiDT2
 * @Last Modified time: 2018-12-11 14:59:15
 */
import { createAsyncTypes } from 'utils/actionUtils';

const PREFIX = 'USER_MANAGEMENT_';
export const NA = 'N/A';

export const actionTypes = {
  GET_DATA_USER: createAsyncTypes(`${PREFIX}GET_DATA_USER`),
  GET_ROLES: createAsyncTypes(`${PREFIX}GET_ROLES`),
  POST_CREATE_USER: createAsyncTypes(`${PREFIX}POST_CREATE_USER`),
  DELETE_USER: createAsyncTypes(`${PREFIX}DELETE_USER`),
  GET_USER_INFORMATION_BY_ID: createAsyncTypes(
    `${PREFIX}GET_USER_INFORMATION_BY_ID`,
  ),
  GET_USER_INFORMATION_BY_NAME: createAsyncTypes(
    `${PREFIX}GET_USER_INFORMATION_BY_NAME`,
  ),
  UPLOAD_IMAGE: createAsyncTypes(`${PREFIX}UPLOAD_IMAGE`),
  UPDATE_USER: createAsyncTypes(`${PREFIX}UPDATE_USER`),
  ACTIVE_USER: createAsyncTypes(`${PREFIX}ACTIVE_USER`),
  CHANGE_IMG: `${PREFIX}CHANGE_IMG`,
  UPLOAD_FILES_IMAGE: `${PREFIX}UPLOAD_FILES_IMAGE`,
  RESET_DATA: `${PREFIX}RESET_DATA`,
  SELECT_ROW_ID: `${PREFIX}SELECT_ROW_ID`,
  DEACTIVATE_USER: `${PREFIX}DEACTIVATE_USER`,
  GET_USER_LIST: `${PREFIX}GET_USER_LIST`,
  GET_ROLE_INFROMATION: `${PREFIX}GET_ROLE_INFROMATION`,
  GET_NEW_ROLE_INFROMATION: `${PREFIX}GET_NEW_ROLE_INFROMATION`,
  GET_ADDITIONAL_INFROMATION: `${PREFIX}GET_ADDITIONAL_INFROMATION`,
  GET_NEW_ADDITIONAL_INFROMATION: `${PREFIX}GET_NEW_ADDITIONAL_INFROMATION`,
  DELETE_USER_LIST: `${PREFIX}DELETE_USER_LIST`,
  DELETE_IMAGE_ATTACHMENT_FILE: `${PREFIX}DELETE_IMAGE_ATTACHMENT_FILE`,
  UPDATE_ATTACHMENT_FILE_LIST: `${PREFIX}UPDATE_ATTACHMENT_FILE_LIST`,
  GET_IMAGE: createAsyncTypes(`${PREFIX}GET_IMAGE`),
  GET_USER_INFORMATION: `${PREFIX}GET_USER_INFORMATION`,
};
