/*
 * @Author: DanND1 
 * @Date: 2018-11-16 14:49:27 
 * @Last Modified by: NhuHH
 * @Last Modified time: 2018-12-07 16:25:06
 */

import { createAsyncTypes } from 'utils/actionUtils';

const PREFIX = 'ROLE_MANAGEMENT_';

export const actionTypes = {
  GET_ALL_ROLES: createAsyncTypes(`${PREFIX}GET_ALL_ROLES`),
  GET_ROLE_BY_ID: createAsyncTypes(`${PREFIX}GET_ROLE_BY_ID`),
  GET_AUTHORITY_CONFIG: createAsyncTypes(`${PREFIX}GET_AUTHORITY_CONFIG`),
  CREATE_ROLE: createAsyncTypes(`${PREFIX}CREATE_ROLE`),
  UPDATE_ROLE: createAsyncTypes(`${PREFIX}UPDATE_ROLE`),
  DELETE_ROLE: createAsyncTypes(`${PREFIX}DELETE_ROLE`),
  CHANGE_USERS_CHECKED: `${PREFIX}CHANGE_USERS_CHECKED`,
  DELETE_ROLE_LIST: `${PREFIX}DELETE_ROLE_LIST`,
  SELECTED_ROW_ID: `${PREFIX}SELECTED_ROW_ID`,
  INIT_SELECT_USER: `${PREFIX}INIT_SELECT_USER`,
  SELECT_USER: `${PREFIX}SELECT_USER`,
  CHANGE_USERS_LIST: `${PREFIX}CHANGE_USERS_LIST`,
  CHANGE_AUTHORITIES_LIST: `${PREFIX}CHANGE_AUTHORITIES_LIST`,
  DISPLAY_CONFIRMATION_DIALOG: `${PREFIX}DISPLAY_CONFIRMATION_DIALOG`,
  RESET_ROLE_DETAIL: `${PREFIX}RESET_ROLE_DETAIL`,
  RESET_INIT_DATA: `${PREFIX}RESET_INIT_DATA`,
  GET_LIST_ROLE: `${PREFIX}GET_LIST_ROLE`,
};
