apiVersion: v1
kind: Service
metadata:
  name: discovery
  labels:
    app: consul
    tier: backend
spec:
  # comment or delete the following line if you want to use a LoadBalancer
  type: NodePort
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  # type: LoadBalancer
  ports:
  - port: 8300
    name: http
  - port: 8500
    name: dashboard
  selector:
    app: consul
    tier: backend
---
apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: discovery
spec:
  selector:
    matchLabels:
      app: consul
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: consul
        tier: backend
    spec:
      containers:
      - name: consul
        image: consul:0.9.3
        resources:
          requests:
#            cpu: 0.2
#            memory: 100Mi
        ports:
        - containerPort: 8500