apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    app: traefik
    tier: frontend
spec:
  # comment or delete the following line if you want to use a LoadBalancer
  type: LoadBalancer
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  # type: LoadBalancer
  ports:
  - port: 80
    name: http
  - port: 443
    name: https
  - port: 8080
    name: dashboard
  selector:
    app: traefik
    tier: frontend
---
apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: traefik
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: traefik
        tier: frontend
    spec:
      containers:
      - name: traefik
        image: asia.gcr.io/secure-skye/gateway:0.4.0.RELEASE
        resources:
          requests:
#            cpu: 0.2
#            memory: 100Mi
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 8080