apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: oauth2
spec:
  selector:
    matchLabels:
      app: oauth2
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: oauth2
        tier: frontend
    spec:
      containers:
      - name: oauth2
        image: asia.gcr.io/secure-skye/oauth2:0.4.0.RELEASE
        resources:
          requests:
#            cpu: 1
#            memory: 1Gi
        ports:
        - containerPort: 8080