apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: ota-vehicle
spec:
  selector:
    matchLabels:
      app: ota-vehicle
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: ota-vehicle
        tier: frontend
    spec:
      containers:
      - name: ota-vehicle
        image: asia.gcr.io/secure-skye/ota-vehicle:0.4.0.RELEASE
        resources:
          requests:
#            cpu: 1
#            memory: 1Gi
        ports:
        - containerPort: 8080