apiVersion: v1
kind: Service
metadata:
  name: ui
  labels:
    app: ui
    tier: frontend
spec:
  # comment or delete the following line if you want to use a LoadBalancer
  type: NodePort
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  # type: LoadBalancer
  ports:
  - port: 4200
    name: http
  selector:
    app: ui
    tier: frontend
---
apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: ui
spec:
  selector:
    matchLabels:
      app: ui
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: ui
        tier: frontend
    spec:
      containers:
      - name: ui
        image: asia.gcr.io/secure-skye/ui:0.4.0.RELEASE
        resources:
          requests:
#            cpu: 0.2
#            memory: 100Mi
        ports:
        - containerPort: 4200
