apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: user-admin
spec:
  selector:
    matchLabels:
      app: user-admin
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: user-admin
        tier: frontend
    spec:
      containers:
      - name: user-admin
        image: asia.gcr.io/secure-skye/user-admin:0.4.0.RELEASE
        resources:
          requests:
#            cpu: 1
#            memory: 1Gi
        ports:
        - containerPort: 8080