apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: vehicle-message
spec:
  selector:
    matchLabels:
      app: vehicle-message
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: vehicle-message
        tier: frontend
    spec:
      containers:
      - name: vehicle-message
        image: asia.gcr.io/secure-skye/vehicle-message:0.4.0.RELEASE
        resources:
          requests:
#            cpu: 1
#            memory: 1Gi
        ports:
        - containerPort: 8080