/*
 * @Author: NhuHH 
 * @Date: 2018-11-13 08:51:42 
 * @Last Modified by: DanND1
 * @Last Modified time: 2018-12-05 16:28:31
 */
import { createAsyncTypes } from 'utils/actionUtils';

const PREFIX = 'VEHICLE_SOFTWARE_MANAGEMENT_';
export const NA = 'N/A';

export const actionTypes = {
  GET_DATA: createAsyncTypes(`${PREFIX}GET_DATA`),
  CHANGE_BUTTON_FILTER: `${PREFIX}CHANGE_BUTTON_FILTER`,
  CHAMGE_DATE_FILTER: `${PREFIX}CHAMGE_DATE_FILTER`,
  GET_DATE_CHILD: `${PREFIX}CHANGE_DATE_CHILD`,
  GET_BUTTON_ID: `${PREFIX}GET_BUTTON_ID`,
  GET_DATA_UPGRADE_SOFTWARE: createAsyncTypes(
    `${PREFIX}GET_DATA_UPGRADE_SOFTWARE`,
  ),
  HANDLE_SELECT_ROW_ID: `${PREFIX}HANDLE_SELECT_ROW_ID`,
  GET_DATE_TEST: `${PREFIX}GET_DATE_TEST`,
  GET_DATA_OTA_PACKAGE: createAsyncTypes(`${PREFIX}GET_DATA_OTA_PACKAGE`),
  GET_DATE_OTA_TEST: `${PREFIX}GET_DATE_OTA_TEST`,
  CHANGE_STATUS_MODAL_UPGRADE_DETAIL: `${PREFIX}CHANGE_STATUS_MODAL_UPGRADE_DETAIL`,
  HANDLE_UPGRADE_OTA_PACKAGE: createAsyncTypes(
    `${PREFIX}HANDLE_UPGRADE_OTA_PACKAGE`,
  ),
  DOWNLOAD_IMAGE_OF_OTA_PACKAGE_DETAIL: createAsyncTypes(
    `${PREFIX}DOWNLOAD_IMAGE_OF_OTA_PACKAGE_DETAIL`,
  ),
};
