/*
 * @Author: NhuHH 
 * @Date: 2018-11-14 11:39:36 
 * @Last Modified by: NhuHH
 * @Last Modified time: 2018-11-29 14:23:17
 */
const PREFIX = 'ADDITIONAL_INFORMATION_';
export const actionTypes = {
  DELETE_ADDITIONAL_INFORMATION: `${PREFIX}DELETE_ADDITIONAL_INFORMATION`,
  TOOGLE_USER_FORM_ADDITIONAL_INFORMATION: `${PREFIX}TOOGLE_USER_FORM_ADDITIONAL_INFORMATION`,
  ADD_KEY_FORM_ADDITIONAL_INFORMATION: `${PREFIX}ADD_KEY_FORM_ADDITIONAL_INFORMATION`,
  ADD_VALUE_FORM_ADDITIONAL_INFORMATION: `${PREFIX}ADD_VALUE_FORM_ADDITIONAL_INFORMATION`,
  GET_ADDITIONAL_INFROMATION: `${PREFIX}GET_ADDITIONAL_INFROMATION`,
  GET_NEW_ADDITIONAL_INFROMATION: `${PREFIX}GET_NEW_ADDITIONAL_INFROMATION`,
  RESET_DATA: `${PREFIX}RESET_DATA`,
  DISPLAY_ERROR: `${PREFIX}DISPLAY_ERROR`,
};
